<?xml version="1.0" encoding="UTF-8"?>
<!-- Site: http://html5-overview.net -->
<!-- Source: https://github.com/dret/HTML5-overview -->
<!-- This is free and unencumbered data released into the public domain. Anyone is free to copy, modify, publish, use, compile, sell, or distribute this data, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means. Enjoy! -->
<?xml-stylesheet type="text/xsl" href="xml2jekyll.xsl"?>
<!DOCTYPE html5 [
  <!ELEMENT html5 (specs, log) >
  <!ELEMENT specs (spec*) >
  <!ELEMENT spec (title, abstract) >
  <!ATTLIST spec
    id        CDATA                                                            #REQUIRED
    status    ( WD | CR | PER | PR | REC | SPSD | NOTE | other | abandoned )   #REQUIRED
    ed        CDATA                                                            #IMPLIED
    >
  <!ELEMENT title (#PCDATA) >
  <!ELEMENT abstract (#PCDATA | q | em)* >
  <!ELEMENT q (#PCDATA) >
  <!ELEMENT em (#PCDATA) >
  <!ELEMENT log (entry|rename)* >
  <!ELEMENT entry (#PCDATA | q | em | a)* >
  <!ATTLIST entry
    date      CDATA                                                            #REQUIRED
    >
  <!ELEMENT a (#PCDATA | q)* >
  <!ATTLIST a
    href      CDATA                                                            #REQUIRED
    >
  <!ELEMENT rename (old, new) >
  <!ATTLIST rename
    date      CDATA                                                            #REQUIRED
    >
  <!ELEMENT old EMPTY >
  <!ATTLIST old
    id        CDATA                                                            #REQUIRED
    title     CDATA                                                            #REQUIRED
    >
  <!ELEMENT new EMPTY >
  <!ATTLIST new
    id        CDATA                                                            #REQUIRED
    title     CDATA                                                            #REQUIRED
    >
]>
<html5>
    <specs>
        <spec id="html5" status="SPSD">
            <title>HTML5</title>
            <abstract>This specification defines the 5th major revision of the core language of the World Wide Web: the Hypertext Markup Language (HTML). In this version, new features are introduced to help Web application authors, new elements are introduced based on research into prevailing authoring practices, and special attention has been given to defining clear conformance criteria for user agents in an effort to improve interoperability.</abstract>
        </spec>
        <spec id="html51" status="REC">
            <title>HTML 5.1</title>
            <abstract>This specification defines the 2nd edition of the 5th major version, first minor revision of the core language of the World Wide Web: the Hypertext Markup Language (HTML). In this version, a significant error with HTML 5.1 has been rectified, as noted in the Errata corrected section. Meanwhile, new features continue to be introduced to help Web application authors, new elements continue to be introduced based on research into prevailing authoring practices, and special attention continues to be given to defining clear conformance criteria for user agents in an effort to improve interoperability in the development of HTML 5.2.</abstract>
        </spec>
        <spec id="html52" status="REC">
            <title>HTML 5.2</title>
            <abstract>This specification defines the 5th major version, second minor revision of the core language of the World Wide Web: the Hypertext Markup Language (HTML). In this version, new features continue to be introduced to help Web application authors, new elements continue to be introduced based on research into prevailing authoring practices, and special attention continues to be given to defining clear conformance criteria for user agents in an effort to improve interoperability.</abstract>
        </spec>
        <spec id="html53" status="WD">
            <title>HTML 5.3</title>
            <abstract>This specification defines the 5th major version, third minor revision of the core language of the World Wide Web: the Hypertext Markup Language (HTML). In this version, new features continue to be introduced to help Web application authors, new elements continue to be introduced based on research into prevailing authoring practices, and special attention continues to be given to defining clear conformance criteria for user agents in an effort to improve interoperability.</abstract>
        </spec>
        <spec id="MathML3" status="REC">
            <title>Mathematical Markup Language (MathML) Version 3.0</title>
            <abstract> This specification defines the Mathematical Markup Language, or MathML. MathML is a markup language for describing mathematical notation and capturing both its structure and content. The goal of MathML is to enable mathematics to be served, received, and processed on the World Wide Web, just as HTML has enabled this functionality for text. This specification of the markup language MathML is intended primarily for a readership consisting of those who will be developing or implementing renderers or editors using it, or software that will communicate using MathML as a protocol for input or output. It is not a User's Guide but rather a reference document. MathML can be used to encode both mathematical notation and mathematical content. About thirty-eight of the MathML tags describe abstract notational structures, while another about one hundred and seventy provide a way of unambiguously specifying the intended meaning of an expression. Additional chapters discuss how the MathML content and presentation elements interact, and how MathML renderers might be implemented and should interact with browsers. Finally, this document addresses the issue of special characters used for mathematics, their handling in MathML, their presence in Unicode, and their relation to fonts. While MathML is human-readable, authors typically will use equation editors, conversion programs, and other specialized software tools to generate MathML. Several versions of such MathML tools exist, both freely available software and commercial products, and more are under development.</abstract>
        </spec>
        <spec id="system-info-api" status="NOTE">
            <title>System Information API</title>
            <abstract>This specification defines an API to provide Web applications with access to various properties of the system which they are running on. Specifically, properties pertaining to the device hardware are addressed. Examples include battery status, current network bandwidth. Additionally, some of those properties offer access to the environment around the device, such as ambient brightness or atmospheric pressure.</abstract>
        </spec>
        <spec id="vehicle-information-api" status="NOTE">
            <title>Vehicle Information API Specification</title>
            <abstract>This specification defines a high level API for accessing to vehicle signals and data attributes. The purpose of the specification is to promote a client implementation with a standard API that enables application development in a consistent manner across participating automotive manufacturers.</abstract>
        </spec>
        <spec id="telephony" status="NOTE">
            <title>Web Telephony API</title>
            <abstract>This specification defines an API to manage telephone calls. A typical use case of the Web Telephony API is the implementation of a 'Dialer' application supporting multiparty calls and multiple telephony services. A minimal structure for call history items is also defined.</abstract>
        </spec>
        <spec id="discovery-api" status="NOTE">
            <title>Network Service Discovery</title>
            <abstract>This specification defines a mechanism for an HTML document to discover and subsequently communicate with HTTP-based services advertised via common discovery protocols within the current network.</abstract>
        </spec>
        <spec id="generic-sensor" status="CR">
            <title>Generic Sensor API</title>
            <abstract>This specification defines a framework for exposing sensor data to the Open Web Platform in a consistent way. It does so by defining a blueprint for writing specifications of concrete sensors along with an abstract Sensor interface that can be extended to accommodate different sensor types.</abstract>
        </spec>
        <spec id="ambient-light" status="CR">
            <title>Ambient Light Sensor</title>
            <abstract>This specification defines a concrete sensor interface to monitor the ambient light level or illuminance of the device's environment.</abstract>
        </spec>
        <spec id="magnetometer" status="CR">
            <title>Magnetometer Sensor</title>
            <abstract>This specification defines a concrete sensor interface to measure magnetic field in the X, Y and Z axis.</abstract>
        </spec>
        <spec id="gyroscope" status="CR">
            <title>Gyroscope Sensor</title>
            <abstract>This specification defines a concrete sensor interface to monitor the rate of rotation around the device's local three primary axes.</abstract>
        </spec>
        <spec id="accelerometer" status="CR">
            <title>Accelerometer Sensor</title>
            <abstract>This specification defines accelerometer sensor interface for obtaining information about acceleration applied to the X, Y and Z axis of a device that hosts the sensor.</abstract>
        </spec>
        <spec id="motion-sensors" status="NOTE">
            <title>Motion Sensors Explainer</title>
            <abstract>This explainer is an introduction to low-level and high-level motion sensors, their relationship, inner workings and common use-cases. Common cases of event filtering and sensor fusion are introduced with examples, showing how to apply that on sensors following the Generic Sensor API specification.</abstract>
        </spec>
        <spec id="orientation-sensor" status="CR">
            <title>Orientation Sensor</title>
            <abstract>This specification defines a base orientation sensor interface and concrete sensor subclasses to monitor the device's physical orientation in relation to a stationary three dimensional Cartesian coordinate system.</abstract>
        </spec>
        <spec id="audioproc" status="WD">
            <title>Audio Processing API</title>
            <abstract>This specification introduces and compares two client-side APIs for processing and synthesizing real-time audio streams in the browser.</abstract>
        </spec>
        <spec id="html-transcript-src" status="NOTE">
            <title>A Transcript Extension for HTML</title>
            <abstract>This document describes an extension to HTML which explicitly identifies a transcript linked to a media object such as audio or video. It was created to meet requirements for transcriptions that are described in the Media Accessibility User Requirements (MAUR).</abstract>
        </spec>
        <spec id="html-picture-element" status="NOTE">
            <title>The picture Element</title>
            <abstract>This specification defines the HTML picture element and extends the img and source elements to allow authors to declaratively control or give hints to the user agent about which image resource to use, based on the screen pixel density, viewport size, image format, and other factors.</abstract>
        </spec>
        <spec id="html-longdesc" status="REC">
            <title>HTML Image Description Extension (longdesc)</title>
            <abstract>This specification defines a longdesc attribute (based on the longdesc attribute of HTML 4) to link descriptions to images in HTML5 content. By allowing a hyperlink inside another one, this document explicitly redefines the HTML concept of hyperlink in a limited set of circumstances.</abstract>
        </spec>
        <spec id="html-srcset" status="NOTE">
            <title>The srcset Attribute</title>
            <abstract>When authors adapt their sites for high-resolution displays, they often need to be able to use different assets representing the same image. We address this need for adaptive, bitmapped content images by adding a srcset attribute to the img element.</abstract>
        </spec>
        <spec id="media-source" status="REC">
            <title>Media Source Extensions</title>
            <abstract>This specification extends HTMLMediaElement to allow JavaScript to generate media streams for playback. Allowing JavaScript to generate streams facilitates a variety of use cases like adaptive streaming and time shifting live streams.</abstract>
        </spec>
        <spec id="remote-playback" status="CR">
            <title>Remote Playback API</title>
            <abstract>This specification defines an API extending the HTMLMediaElement that enables controlling remote playback of media from a web page.</abstract>
        </spec>
        <spec id="webvtt1" status="WD">
            <title>WebVTT: The Web Video Text Tracks Format</title>
            <abstract>This specification defines WebVTT, the Web Video Text Tracks format. Its main use is for marking up external text track resources in connection with the HTML &lt;track> element. WebVTT files provide captions or subtitles for video content, and also text video descriptions, chapters for content navigation, and more generally any form of metadata that is time-aligned with audio or video content.</abstract>
        </spec>
        <spec id="webmidi" status="WD">
            <title>Web MIDI API</title>
            <abstract> Some user agents have connected music devices, such as synthesizers, keyboard and other controllers, and drum machines. The widely adopted Musical Instrument Digital Interface (MIDI) protocol enables electronic musical instruments, controllers and computers to communicate and synchronize with each other. MIDI does not transmit audio signals: instead, it sends event messages about musical notes, controller signals for parameters such as volume, vibrato and panning, cues and clock signals to set the tempo, and system-specific MIDI communications (e.g. to remotely store synthesizer-specific patch data). This same protocol has become a standard for non-musical uses, such as show control, lighting and special effects control. This specification defines an API supporting the MIDI protocol, enabling web applications to enumerate and select MIDI input and output devices on the client system and send and receive MIDI messages. It is intended to enable non-music MIDI applications as well as music ones, by providing low-level access to the MIDI devices available on the users' systems. At the same time, the Web MIDI API is not intended to become a semantic controller platform; it is designed to expose the mechanics of MIDI input and output interfaces, and the practical aspects of sending and receiving MIDI messages, without identifying what those actions might mean semantically. To some users, "MIDI" has become synonymous with Standard MIDI Files and General MIDI. That is not the intent of this API; the use case of simply playing back a .SMF file is not within the purview of this specification (it could be considered a different format to be supported by the HTML5 &lt;audio> element, for example). The Web MIDI API is intended to enable direct access to devices that respond to MIDI - external synthesizers or lighting systems, for example, or even the software synthesizers that are built in to many common operating systems. The Web MIDI API is also explicitly designed to enable a new class of applications on the web that can respond to MIDI controller inputs - using external hardware controllers with physical buttons, knobs and sliders (as well as musical controllers like keyboard, guitar or wind instrument controllers) to control web applications. The Web MIDI API is also expected to be used in conjunction with other APIs and elements of the web platform, notably the Web Audio API and High-Resolution Time. This API is also intended to be familiar to users of MIDI APIs on other systems, such as Apple's CoreMIDI and Microsoft's Windows MIDI API.</abstract>
        </spec>
        <spec id="battery-status" status="CR">
            <title>Battery Status API</title>
            <abstract>This specification defines an API that provides information about the battery status of the hosting device.</abstract>
        </spec>
        <spec id="wake-lock" status="CR">
            <title>Wake Lock API</title>
            <abstract>This document specifies an API that allows web applications to request a wake lock. A wake lock prevents some aspect of the device from entering a power-saving state (e.g., preventing the system from turning off the screen).</abstract>
        </spec>
        <spec id="audio-output" status="CR">
            <title>Audio Output Devices API</title>
            <abstract>This document defines a set of JavaScript APIs that let a Web application manage how audio is rendered on the user audio output devices.</abstract>
        </spec>
        <spec id="calendar-api" status="NOTE">
            <title>Calendar API</title>
            <abstract>The Calendar API defines the high-level interfaces required to obtain read access to a user's calendaring service.</abstract>
        </spec>
        <spec id="clipboard-apis" status="WD">
            <title>Clipboard API and Events</title>
            <abstract>This document describes APIs for clipboard operations such as copy, cut and paste in web applications.</abstract>
        </spec>
        <spec id="orientation-event" status="NOTE">
            <title>DeviceOrientation Event Specification</title>
            <abstract>This specification defines several new DOM event types that provide information about the physical orientation and motion of a hosting device.</abstract>
        </spec>
        <spec id="app-uri" status="NOTE">
            <title>The app: URL scheme</title>
            <abstract>This specification defines the app: URL scheme. The app: URL scheme can be used by packaged applications to obtain resources that are inside a container. These resources can then be used with web platform features that accept URLs.</abstract>
        </spec>
        <spec id="FileAPI" status="WD">
            <title>File API</title>
            <abstract>This specification provides an API for representing file objects in web applications, as well as programmatically selecting them and accessing their data.</abstract>
        </spec>
        <spec id="file-system-api" status="NOTE">
            <title>File API: Directories and System</title>
            <abstract>This specification defines an API to navigate file system hierarchies, and defines a means by which a user agent may expose sandboxed sections of a user's local filesystem to web applications. It builds on <q>File API: Writer</q>, which in turn built on <q>File API</q>, each adding a different kind of functionality.</abstract>
        </spec>
        <spec id="file-writer-api" status="NOTE">
            <title>File API: Writer</title>
            <abstract>This specification defines an API for writing to files from web applications. This API is designed to be used in conjunction with, and depends on definitions in, other APIs and elements on the web platform. Most relevant among these are <em>File API</em> and <em>Web Workers</em>.</abstract>
        </spec>
        <spec id="http://w3c.github.io/filesystem-api/" status="other">
            <title>FileSystem API</title>
            <abstract>The FileSystem API defines functionality on a local sandboxed file system within the same origin of the Web Application that created it. It exposes standard file system operations to Web Applications, such as creation of files and directories, and reading and writing of them (from and to disk), including other programmatic manipulation of files and directories.</abstract>
        </spec>
        <spec id="http://w3c.github.io/webvr/" status="abandoned">
            <title>WebVR</title>
            <abstract>This specification describes support for accessing virtual reality (VR) devices, including sensors and head-mounted displays on the Web.</abstract>
        </spec>
        <spec id="webxr" status="WD">
            <title>WebXR Device API</title>
            <abstract>This specification describes support for accessing virtual reality (VR) and augmented reality (AR) devices, including sensors and head-mounted displays, on the Web.</abstract>
        </spec>
        <spec id="wai-aria" status="REC">
            <title>Accessible Rich Internet Applications (WAI-ARIA) 1.0</title>
            <abstract>Accessibility of web content requires semantic information about widgets, structures, and behaviors, in order to allow assistive technologies to convey appropriate information to persons with disabilities. This specification provides an ontology of roles, states, and properties that define accessible user interface elements and can be used to improve the accessibility and interoperability of web content and applications. These semantics are designed to allow an author to properly convey user interface behaviors and structural information to assistive technologies in document-level markup.</abstract>
        </spec>
        <spec id="wai-aria-1.1" status="CR">
            <title>Accessible Rich Internet Applications (WAI-ARIA) 1.1</title>
            <abstract>Accessibility of web content requires semantic information about widgets, structures, and behaviors, in order to allow assistive technologies to convey appropriate information to persons with disabilities. This specification provides an ontology of roles, states, and properties that define accessible user interface elements and can be used to improve the accessibility and interoperability of web content and applications. These semantics are designed to allow an author to properly convey user interface behaviors and structural information to assistive technologies in document-level markup. This version adds features new since WAI-ARIA 1.0 to improve interoperability with assistive technologies to form a more consistent accessibility model for HTML5 and SVG2. This specification complements both HTML5 and SVG2.</abstract>
        </spec>
        <spec id="html-aam-1.0" status="WD">
            <title>HTML Accessibility API Mappings 1.0</title>
            <abstract>HTML Accessibility API Mappings (HTML-AAM) defines how user agents map HTML 5.1 elements and attributes to platform accessibility application programming interfaces (APIs). It leverages and extends the Core Accessibility API Mappings 1.1 and the Accessible Name and Description: Computation and API Mappings 1.1 for use with the HTML 5.1 host language. Documenting these mappings promotes interoperable exposure of roles, states, properties, and events implemented by accessibility APIs and helps to ensure that this information appears in a manner consistent with author intent.</abstract>
        </spec>
        <spec id="html-aria" status="WD">
            <title>ARIA in HTML</title>
            <abstract>This specification defines the web developer rules (author conformance requirements) for the use of WAI-ARIA attributes on HTML 5.1 elements. It also defines requirements for Conformance Checking tools.</abstract>
        </spec>
        <spec id="fullscreen" status="NOTE">
            <title>Fullscreen</title>
            <abstract>Fullscreen defines the fullscreen API for the web platform.</abstract>
        </spec>
        <spec id="gamepad" status="WD">
            <title>Gamepad</title>
            <abstract>The Gamepad specification defines a low-level interface that represents gamepad devices.</abstract>
        </spec>
        <spec id="geolocation-API" status="REC">
            <title>Geolocation API Specification</title>
            <abstract>This specification defines an API that provides scripted access to geographical location information associated with the hosting device.</abstract>
        </spec>
        <spec id="geolocation-API-v2" status="NOTE">
            <title>Geolocation API Specification Level 2</title>
            <abstract>This specification defines an API that provides scripted access to geographical location information associated with the hosting device, and this Level 2 version extends the capability of the Geolocation API Specification by adding the ability to get location represented as a civil address.</abstract>
        </spec>
        <spec id="geolocation-sensor" status="WD">
            <title>Geolocation Sensor</title>
            <abstract>This specification defines the GeolocationSensor interface for obtaining geolocation of the hosting device.</abstract>
        </spec>
        <spec id="geofencing" status="NOTE">
            <title>Geofencing API</title>
            <abstract>This specification defines an API that lets webapps setup geographic boundaries around specific locations and then receive notifications when the hosting device enters or leaves those areas.</abstract>
        </spec>
        <spec id="nfc" status="NOTE">
            <title>Web NFC API</title>
            <abstract>Near Field Communication (NFC) is an international standard (ISO/IEC 18092) that specifies an interface and protocol for simple wireless interconnection of closely coupled devices operating at 13.56 MHz. There are three groups of application scenarios for NFC: The first one is to hold a device close to a wireless tag to exchange some digital information or data; The second is to hold two devices close to each other in order to exchange some information or data between them; The third one is to make payments by holding mobile phones close to point of sales terminals instead of swiping smart cards. NFC enables wireless communication between two devices at close proximity, usually less than a few centimeters.</abstract>
        </spec>
        <spec id="payment-request" status="CR">
            <title>Payment Request API</title>
            <abstract>This specification describes a web API to allow merchants (i.e. web sites selling physical or digital goods) to easily accept payments from different payment methods with minimal integration. User agents (e.g. browsers) will facilitate the payment flow between merchant and user.</abstract>
        </spec>
        <spec id="payment-handler" status="WD">
            <title>Payment Handler API</title>
            <abstract>The Payment Request API provides a standard way to initiate payment requests from Web pages and applications. User agents implementing that API prompt the user to select a way to handle the payment request, after which the user agent returns a payment response to the originating site. This specification defines capabilities that enable Web applications to handle payment requests.</abstract>
        </spec>
        <spec id="payment-method-id" status="CR">
            <title>Payment Method Identifiers</title>
            <abstract>The Payment Request API requires that merchants supply a list identifiers for supported payment methods. This document defines those identifier strings and how they are created.</abstract>
        </spec>
        <spec id="payment-method-basic-card" status="WD">
            <title>Payment Method: Basic Card</title>
            <abstract>This specification describes data structures and formats, and a simple processing model, to facilitate card-based payments on the Web. It is used by other specifications to facilitate monetary transactions with a "basic card", such as credit, debit, or prepaid card.</abstract>
        </spec>
        <spec id="payment-method-manifest" status="WD">
            <title>Payment Method Manifest</title>
            <abstract>This specification defines the machine-readable manifest file, known as a payment method manifest, describing how a payment method participates in the Web Payments ecosystem, and how such files are to be used.</abstract>
        </spec>
        <spec id="webpayments-http-api" status="NOTE">
            <title>Web Payments HTTP API 1.0</title>
            <abstract>This document outlines how to register payment applications, create payment requests, and reply with payment responses using a standard HTTP API.</abstract>
        </spec>
        <spec id="webpayments-http-messages" status="WD">
            <title>Web Payments HTTP Messages 1.0</title>
            <abstract>This document specifies the Web Payments messages that are used to initiate and acknowledge a payment request via the HTTP protocol. The messages are typically passed between the software ecosystem that initiates, executes, and finalizes Web Payments.</abstract>
        </spec>
        <spec id="2dcontext" status="REC">
            <title>HTML Canvas 2D Context</title>
            <abstract>This specification defines the 2D Context for the HTML canvas element. The 2D Context provides objects, methods, and properties to draw and manipulate graphics on a canvas drawing surface.</abstract>
        </spec>
        <spec id="2dcontext2" status="NOTE">
            <title>HTML Canvas 2D Context, Level 2</title>
            <abstract>This specification defines the 2D Context for the HTML canvas element. The 2D Context provides objects, methods, and properties to draw and manipulate graphics on a canvas drawing surface.</abstract>
        </spec>
        <spec id="html-media-capture" status="REC">
            <title>HTML Media Capture</title>
            <abstract>This specification defines HTML form enhancements that provide access to the audio, image and video capture capabilities of the device.</abstract>
        </spec>
        <spec id="screen-capture" status="WD">
            <title>Screen Capture</title>